language: node_js
cache: yarn, pip
services:
  - docker
node_js:
  - "10.16.0"
env:
  global:
  - DOCKER_REPO=transparent-path/react-ui
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add gulp-cli
  - yarn install
  - pip install awscli
script:
  - yarn run init
  - yarn run build-prod
  - docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash scripts/deploy-aws.sh
  on:
    branch: master
